services:
  # www:
  #   build:
  #     context: ../youtubersite
  #     dockerfile: ../youtubersite/Dockerfile
  #   container_name: www
  #   ports:
  #     - "2999:3000"
  #   volumes:
  #     - ../youtubersite:/app
  #     - www_node_modules:/app/node_modules
  api:
    build:
      context: ../liiinx-api
      dockerfile: ../liiinx-api/Dockerfile
    container_name: api
    ports:
      - "3001:3001"
    volumes:
      - ../liiinx-api:/app
      - api_node_modules:/app/node_modules
    environment:
      - AWS_ENDPOINT=liiinx_localstack_container
      - AWS_REGION=us-east-2
      - AWS_ACCOUNT_ID=000000000000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - REDIS_HOST=liiinx_redis_container
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://liiinx_mongodb_container:27017
    networks:
      - liiinx_network
volumes:
  www_node_modules:
  app_node_modules:
  api_node_modules:

networks:
  liiinx_network:
    external: true
    name: liiinx_network
